name = "Nonconvex"
uuid = "01bcebdf-4d21-426d-b5c4-6132c1619978"
authors = ["Mohamed Tarek <mohamed82008@gmail.com> and contributors"]
version = "0.7.0"

[deps]
ADNLPModels = "54578032-b7ea-4c30-94aa-7cbd1cce6c9a"
AbstractGPs = "99985d1d-32ba-4be9-9821-2ec096f28918"
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
NLPModelsModifiers = "e01155f1-5c6f-4375-a9d8-616dd036575f"
NamedTupleTools = "d9ec5142-1e00-5aa0-9d6a-321866360f50"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
Sobol = "ed01d8cd-4d21-5b2a-85b4-cc3bdc58bad4"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
ADNLPModels = "0.1"
AbstractGPs = "0.3"
Cbc = "0.8"
ChainRulesCore = "0.10"
ForwardDiff = "0.10"
IntervalArithmetic = "0.17, 0.18"
Ipopt = "0.6"
JuMP = "0.21"
Juniper = "0.7"
MathOptInterface = "0.9"
NLPModelsModifiers = "0.1, 0.4"
NamedTupleTools = "0.13"
Optim = "1.2"
OrderedCollections = "1.4"
Parameters = "0.12"
Percival = "0.3.1"
PyPlot = "2.9"
Reexport = "1"
Requires = "1"
Setfield = "0.7"
Sobol = "1"
Zygote = "0.6"
julia = "1"

[extras]
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
Hyperopt = "93e5fe13-2215-51db-baaf-2e9a34fb2712"
Juniper = "2ddba703-00a4-53a7-87a5-e8b9971dde84"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
Pavito = "cd433a01-47d1-575d-afb7-6db927ee8d8f"
Percival = "01435c0c-c90d-11e9-3788-63660f8fbccc"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["FiniteDifferences", "Hyperopt", "Juniper", "NLopt", "Pavito", "Percival", "SafeTestsets", "Test"]
